 
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
before_script:
  - composer self-update
  - composer install
  - cp ruleset.xml.dist ruleset.xml
script:
  - php vendor/bin/phpcs --standard=ruleset.xml
